import { Group } from '../types';

export const INITIAL_GROUPS: Group[] = [
  {
    id: 'group_tahoe',
    name: 'Lake Tahoe Cabin Trip',
    currency: 'USD',
    currencySymbol: '$',
    createdAt: '2026-09-18T10:00:00.000Z',
    friends: [
      {
        id: 'f_alex',
        name: 'Alex Rivera',
        email: 'alex.rivera@example.com',
        phone: '+1 415-555-0142',
        upiId: '@alex-rivera',
        color: '#3B82F6', // Blue
        notes: 'Group trip coordinator',
      },
      {
        id: 'f_sarah',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.com',
        phone: '+1 415-555-0189',
        upiId: '@sarah-chen',
        color: '#10B981', // Emerald
        notes: 'Keeps all grocery receipts',
      },
      {
        id: 'f_mike',
        name: 'Mike Kowalski',
        email: 'mike.k@example.com',
        phone: '+1 510-555-0123',
        upiId: '@mike-k',
        color: '#F59E0B', // Amber
        notes: 'Prefers Venmo or Cash',
      },
      {
        id: 'f_priya',
        name: 'Priya Sharma',
        email: 'priya.s@example.com',
        phone: '+1 408-555-0177',
        upiId: '@priya-sharma',
        color: '#8B5CF6', // Purple
        notes: 'Driver for rental SUV',
      },
      {
        id: 'f_david',
        name: 'David Miller',
        email: 'david.m@example.com',
        phone: '+1 650-555-0164',
        upiId: '@david-miller',
        color: '#EC4899', // Pink
        notes: 'Water sports coordinator',
      },
    ],
    bills: [
      {
        id: 'bill_airbnb',
        groupId: 'group_tahoe',
        title: 'Lakeside Timber Chalet (3 Nights)',
        category: 'Lodging',
        totalAmount: 1450.0,
        date: '2026-09-19',
        payers: [{ friendId: 'f_alex', amount: 1450.0 }],
        splitType: 'EQUAL',
        participants: [
          { friendId: 'f_alex', shareAmount: 290.0 },
          { friendId: 'f_sarah', shareAmount: 290.0 },
          { friendId: 'f_mike', shareAmount: 290.0 },
          { friendId: 'f_priya', shareAmount: 290.0 },
          { friendId: 'f_david', shareAmount: 290.0 },
        ],
        notes: '3-night stay booked on Airbnb with hot tub and private deck',
        createdAt: '2026-09-19T14:30:00.000Z',
      },
      {
        id: 'bill_costco',
        groupId: 'group_tahoe',
        title: 'Costco Wholesale BBQ & Breakfast Supplies',
        category: 'Groceries',
        totalAmount: 325.4,
        date: '2026-09-20',
        payers: [{ friendId: 'f_sarah', amount: 325.4 }],
        splitType: 'EQUAL',
        participants: [
          { friendId: 'f_alex', shareAmount: 65.08 },
          { friendId: 'f_sarah', shareAmount: 65.08 },
          { friendId: 'f_mike', shareAmount: 65.08 },
          { friendId: 'f_priya', shareAmount: 290.0 }, // will be recalculated properly in storage
          { friendId: 'f_david', shareAmount: 65.08 },
        ],
        notes: 'Steaks, veggies, eggs, snacks, and morning coffee beans',
        createdAt: '2026-09-20T11:15:00.000Z',
      },
      {
        id: 'bill_dinner',
        groupId: 'group_tahoe',
        title: 'Timber Smokehouse Craft Dinner',
        category: 'Dining',
        totalAmount: 215.0,
        date: '2026-09-21',
        payers: [{ friendId: 'f_mike', amount: 215.0 }],
        splitType: 'EXACT',
        participants: [
          { friendId: 'f_alex', shareAmount: 42.0 },
          { friendId: 'f_sarah', shareAmount: 38.0 },
          { friendId: 'f_mike', shareAmount: 55.0 },
          { friendId: 'f_priya', shareAmount: 40.0 },
          { friendId: 'f_david', shareAmount: 40.0 },
        ],
        notes: 'Individual dishes plus shared brisket and smoked wings',
        createdAt: '2026-09-21T20:45:00.000Z',
      },
      {
        id: 'bill_gas',
        groupId: 'group_tahoe',
        title: 'SUV Highway Gas & Bay Area Tolls',
        category: 'Transport',
        totalAmount: 92.5,
        date: '2026-09-22',
        payers: [{ friendId: 'f_priya', amount: 92.5 }],
        splitType: 'EQUAL',
        participants: [
          { friendId: 'f_alex', shareAmount: 23.13 },
          { friendId: 'f_sarah', shareAmount: 23.12 },
          { friendId: 'f_mike', shareAmount: 23.12 },
          { friendId: 'f_priya', shareAmount: 23.13 },
        ],
        notes: 'Car pool fuel for the Bay Area to Tahoe drive (David flew in separately)',
        createdAt: '2026-09-22T09:30:00.000Z',
      },
      {
        id: 'bill_kayak',
        groupId: 'group_tahoe',
        title: 'Emerald Bay Kayak & Paddleboard Gear',
        category: 'Entertainment',
        totalAmount: 180.0,
        date: '2026-09-22',
        payers: [{ friendId: 'f_david', amount: 180.0 }],
        splitType: 'SHARES',
        participants: [
          { friendId: 'f_alex', shareAmount: 60.0, shares: 2 }, // Alex rented double kayak
          { friendId: 'f_sarah', shareAmount: 30.0, shares: 1 },
          { friendId: 'f_mike', shareAmount: 30.0, shares: 1 },
          { friendId: 'f_priya', shareAmount: 30.0, shares: 1 },
          { friendId: 'f_david', shareAmount: 30.0, shares: 1 },
        ],
        notes: 'Afternoon lake rentals at Camp Richardson marina',
        createdAt: '2026-09-22T16:00:00.000Z',
      },
    ],
    settlements: [
      {
        id: 'settle_1',
        groupId: 'group_tahoe',
        fromFriendId: 'f_david',
        toFriendId: 'f_alex',
        amount: 100.0,
        date: '2026-09-23',
        paymentMethod: 'Venmo',
        notes: 'Advance settlement for cabin booking',
        createdAt: '2026-09-23T18:00:00.000Z',
      },
    ],
    recurringExpenses: [
      {
        id: 'rec_storage',
        groupId: 'group_tahoe',
        title: 'Tahoe Gear Lockup Rental',
        category: 'Utilities',
        amount: 45.0,
        frequency: 'Monthly',
        payerId: 'f_alex',
        splitType: 'EQUAL',
        participantIds: ['f_alex', 'f_sarah', 'f_mike', 'f_priya', 'f_david'],
        nextDueDate: '2026-10-15',
        active: true,
      },
    ],
    activityLogs: [
      {
        id: 'act_1',
        groupId: 'group_tahoe',
        action: 'BILL_ADDED',
        description: 'Alex Rivera added "Lakeside Timber Chalet (3 Nights)" ($1,450.00)',
        timestamp: '2026-09-19T14:30:00.000Z',
      },
      {
        id: 'act_2',
        groupId: 'group_tahoe',
        action: 'BILL_ADDED',
        description: 'Sarah Chen added "Costco Wholesale BBQ & Breakfast Supplies" ($325.40)',
        timestamp: '2026-09-20T11:15:00.000Z',
      },
      {
        id: 'act_3',
        groupId: 'group_tahoe',
        action: 'BILL_ADDED',
        description: 'Mike Kowalski added "Timber Smokehouse Craft Dinner" ($215.00)',
        timestamp: '2026-09-21T20:45:00.000Z',
      },
      {
        id: 'act_4',
        groupId: 'group_tahoe',
        action: 'SETTLEMENT_RECORDED',
        description: 'David Miller paid $100.00 to Alex Rivera via Venmo',
        timestamp: '2026-09-23T18:00:00.000Z',
      },
    ],
  },
  {
    id: 'group_flat',
    name: 'Apartment 4B Flatmates',
    currency: 'USD',
    currencySymbol: '$',
    createdAt: '2026-09-01T08:00:00.000Z',
    friends: [
      {
        id: 'f_jordan',
        name: 'Jordan Taylor',
        email: 'jordan.t@example.com',
        upiId: '@jordan-taylor',
        color: '#06B6D4',
      },
      {
        id: 'f_samira',
        name: 'Samira Patel',
        email: 'samira.p@example.com',
        upiId: '@samira-patel',
        color: '#10B981',
      },
      {
        id: 'f_marcus',
        name: 'Marcus Vance',
        email: 'marcus.v@example.com',
        upiId: '@marcus-vance',
        color: '#F97316',
      },
    ],
    bills: [
      {
        id: 'bill_fiber',
        groupId: 'group_flat',
        title: 'Gigabit Fiber Internet (September)',
        category: 'Utilities',
        totalAmount: 79.99,
        date: '2026-09-05',
        payers: [{ friendId: 'f_jordan', amount: 79.99 }],
        splitType: 'EQUAL',
        participants: [
          { friendId: 'f_jordan', shareAmount: 26.67 },
          { friendId: 'f_samira', shareAmount: 26.66 },
          { friendId: 'f_marcus', shareAmount: 26.66 },
        ],
        notes: 'Monthly 1 Gbps high-speed Wi-Fi',
        createdAt: '2026-09-05T10:00:00.000Z',
      },
      {
        id: 'bill_electric',
        groupId: 'group_flat',
        title: 'ConEdison Electric & Gas',
        category: 'Utilities',
        totalAmount: 138.45,
        date: '2026-09-12',
        payers: [{ friendId: 'f_samira', amount: 138.45 }],
        splitType: 'EQUAL',
        participants: [
          { friendId: 'f_jordan', shareAmount: 46.15 },
          { friendId: 'f_samira', shareAmount: 46.15 },
          { friendId: 'f_marcus', shareAmount: 46.15 },
        ],
        notes: 'Late summer AC and heating utilities',
        createdAt: '2026-09-12T15:00:00.000Z',
      },
      {
        id: 'bill_cleaning',
        groupId: 'group_flat',
        title: 'Bulk Dishwasher Pods & Paper Towels',
        category: 'Groceries',
        totalAmount: 42.8,
        date: '2026-09-18',
        payers: [{ friendId: 'f_marcus', amount: 42.8 }],
        splitType: 'EQUAL',
        participants: [
          { friendId: 'f_jordan', shareAmount: 14.27 },
          { friendId: 'f_samira', shareAmount: 14.26 },
          { friendId: 'f_marcus', shareAmount: 14.27 },
        ],
        createdAt: '2026-09-18T18:00:00.000Z',
      },
    ],
    settlements: [],
    recurringExpenses: [
      {
        id: 'rec_fiber_apt',
        groupId: 'group_flat',
        title: 'Gigabit Fiber Internet',
        category: 'Utilities',
        amount: 79.99,
        frequency: 'Monthly',
        payerId: 'f_jordan',
        splitType: 'EQUAL',
        participantIds: ['f_jordan', 'f_samira', 'f_marcus'],
        nextDueDate: '2026-10-05',
        active: true,
      },
      {
        id: 'rec_cleaning_apt',
        groupId: 'group_flat',
        title: 'Monthly Bi-weekly Cleaner',
        category: 'Utilities',
        amount: 150.0,
        frequency: 'Monthly',
        payerId: 'f_samira',
        splitType: 'EQUAL',
        participantIds: ['f_jordan', 'f_samira', 'f_marcus'],
        nextDueDate: '2026-10-10',
        active: true,
      },
    ],
    activityLogs: [
      {
        id: 'act_f1',
        groupId: 'group_flat',
        action: 'BILL_ADDED',
        description: 'Jordan Taylor added "Gigabit Fiber Internet" ($79.99)',
        timestamp: '2026-09-05T10:00:00.000Z',
      },
    ],
  },
];
